management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
